import Mathlib.Data.Matrix.Notation
import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.RingTheory.Polynomial.RationalRoot
import Mathlib.Tactic

/-!
Complete formal proof that dim_mat <5,7,16,18> = 3.
Verified with Lean 4.19.0 and Mathlib commit
c44e0c8ee63ca166450922a373c7409c5d26b00b.

This file requires Mathlib only; it does not import the companion project modules.
-/

/-! Source section: SemigroupDimension/Basic.lean -/


/-!
# Matricial dimension of the numerical semigroup generated by 5, 7, 16, 18

All matrices use Mathlib's `Matrix`, all entries are in `ℚ`, and integrality
means membership in the image of integer matrices under entrywise casting.
The target semigroup is defined by arbitrary nonnegative integer combinations
of its four stated generators.
-/

set_option maxHeartbeats 0
set_option maxRecDepth 10000

namespace SemigroupDimension

abbrev QMatrix (n : ℕ) := Matrix (Fin n) (Fin n) ℚ
abbrev ZMatrix (n : ℕ) := Matrix (Fin n) (Fin n) ℤ

def castMatrix (n : ℕ) : ZMatrix n →+* QMatrix n :=
  (Int.castRingHom ℚ).mapMatrix

def IntegralMatrix {n : ℕ} (M : QMatrix n) : Prop :=
  M ∈ (castMatrix n).range

def InSemigroup (n : ℕ) : Prop :=
  ∃ a b c d : ℕ, n = 5 * a + 7 * b + 16 * c + 18 * d

def Realizes {d : ℕ} (M : QMatrix d) : Prop :=
  ∀ n : ℕ, IntegralMatrix (M ^ n) ↔ InSemigroup n

def Realizable (d : ℕ) : Prop := ∃ M : QMatrix d, Realizes M

/-- A dimension is minimal among all matrix representations. -/
def HasMatricialDimension (d : ℕ) : Prop :=
  Realizable d ∧ ∀ k : ℕ, Realizable k → d ≤ k

theorem integralMatrix_iff_den {n : ℕ} (M : QMatrix n) :
    IntegralMatrix M ↔ ∀ i j, (M i j).den = 1 := by
  constructor
  · rintro ⟨N, rfl⟩ i j
    change ((N i j : ℚ)).den = 1
    exact Rat.den_intCast _
  · intro h
    refine ⟨fun i j => (M i j).num, ?_⟩
    ext i j
    exact Rat.coe_int_num_of_den_eq_one (h i j)

theorem integralMatrix_one (n : ℕ) : IntegralMatrix (1 : QMatrix n) :=
  (castMatrix n).range.one_mem

theorem integralMatrix_mul {n : ℕ} {M N : QMatrix n}
    (hM : IntegralMatrix M) (hN : IntegralMatrix N) : IntegralMatrix (M * N) :=
  (castMatrix n).range.mul_mem hM hN

theorem integralMatrix_add {n : ℕ} {M N : QMatrix n}
    (hM : IntegralMatrix M) (hN : IntegralMatrix N) : IntegralMatrix (M + N) :=
  (castMatrix n).range.add_mem hM hN

theorem integralMatrix_pow {n : ℕ} {M : QMatrix n}
    (hM : IntegralMatrix M) (k : ℕ) : IntegralMatrix (M ^ k) :=
  (castMatrix n).range.pow_mem hM k

theorem integralMatrix_int_smul {n : ℕ} (z : ℤ) {M : QMatrix n}
    (hM : IntegralMatrix M) : IntegralMatrix ((z : ℚ) • M) := by
  rcases hM with ⟨N, rfl⟩
  refine ⟨fun i j => z * N i j, ?_⟩
  ext i j
  simp [castMatrix, Matrix.smul_apply, smul_eq_mul]

theorem inSemigroup_zero : InSemigroup 0 := ⟨0, 0, 0, 0, rfl⟩
theorem inSemigroup_five : InSemigroup 5 := ⟨1, 0, 0, 0, rfl⟩
theorem inSemigroup_seven : InSemigroup 7 := ⟨0, 1, 0, 0, rfl⟩

theorem inSemigroup_add {m n : ℕ} (hm : InSemigroup m) (hn : InSemigroup n) :
    InSemigroup (m + n) := by
  rcases hm with ⟨a, b, c, d, rfl⟩
  rcases hn with ⟨e, f, g, h, rfl⟩
  refine ⟨a + e, b + f, c + g, d + h, ?_⟩
  omega

def witness : QMatrix 3 :=
  !![0, 0, -357276958458978899;
    1 / 34522712143931, 0, -833361690 / 1771561;
    0, 214358881, -11]

end SemigroupDimension

/-! Source section: SemigroupDimension/PowerCertificates.lean -/


set_option maxHeartbeats 0
set_option maxRecDepth 10000

namespace SemigroupDimension

/- Each numerical certificate is checked against one ordinary matrix multiplication by Lean. -/
def certificate : ℕ → QMatrix 3
  | 0 => !![1, 0, 0;
      0, 1, 0;
      0, 0, 1]
  | 1 => !![0, 0, -357276958458978899;
      (1 / 34522712143931), 0, (-833361690 / 1771561);
      0, 214358881, -11]
  | 2 => !![0, -76585489022350201192252019, 3930046543048767889;
      0, -100836764490, (-833361689 / 161051);
      (1 / 161051), -2357947691, -100836764369]
  | 3 => !![-2218408817449, 842440379245852213114772209, 36026652474601056590806049731;
      (-833361690 / 285311670611), -1109204408059, 47434718065229;
      (-1 / 14641), -21615255973799511089, 0]
  | 4 => !![24402496991939, 7722632910631363412222859708367511011, 0;
      (-833361689 / 25937424601), 10168053085012973448749, (1388983410219227131 / 1331);
      (-833361689 / 1331), 0, 10168053085012973448749]
  | 5 => !![223697167199216748674681, 0, -3632811079662872354236619579765048947351;
      294532279, 223697167199216748674681, -4783163494193045130918210;
      0, 2179612481251978858956546489869, 111848583264074040738442]
  | 6 => !![0, -778725317920935175099997382341126135264388274231, -39960921636534223563053160892047256135358;
      (1388983410219227131 / 214358881), -1025313574255271152246125998123010, (-1736288344225125146032097011 / 11);
      63135609744819799, 23975737149922238873840840803402, -1025313575485605568150940446245872]
  | 7 => !![-22556898620082286693262504298421301, -8565978445736164881179908512332211624295725414398, 366320915716197826182966321492075780049875013854928;
      -29699682052225972710, -33835347869221876217127445941945881, 482318730202346795831932530705664262;
      694491703026209342, -219785070715203441196204833154905772789232, -22556898538880214967467101033241289]
  | 8 => !![-248125883332200505200546167934674458, 78524141579819479595213161935727614578693332159801862415568, 8059060102238908386192664580886475464877711226560811;
      (-1736288344225125146032097011 / 1771561), 103389303291515962728468521349564331564010822, 21222024116170477626996152548517533898;
      -6366390618410351802540440272, -4835271529624897873465699181799546513037609, 103389303539641846656150885991702442929665001]
  | 9 => !![2274564676507428244363377572893529255017820528, 1727531105427677996325775429967158868685140980366712924412491, -36938615905835380089813678168687227281425429907814934597813899;
      (482318730202346795831932530705664262 / 161051), 4549129342097317589358430651605516775254848138, -48635460089808761677854845986103732841800388809;
      -140060592848726272841938895339, 22162415414126965389986095688339910951369351319223881, 3411847003161257276140770905696789903028533127]
  | 10 => !![50040422612954333634641601609965013969970451761, -7918120371263673446262139550733923279039027239983142535475572435887019, -1218974320016836164142343993021083966227094760343140566215487173;
      131772072922058712004248049055998, -10425442801771565657260647266008537721891281370462162729, -2674950310717177910533933482418941339997854712759;
      641966231439990106588291199630566981451, 731359705740850572266643649822520408905294872175150887, -10425442839301882692034477303557017684555970303776027126]
  | 11 => !![-229359742602252578933466281914966236045882545950133402449, -261297971206544901305885183061071368407481824708118787799658235274133413, 3724770508213717767853140928752034320717449411452463438806579180885614274;
      (-401945951155444311387230132116559775552069329 / 1331), -573399355335936564379972093819757438846580678627595662679, 4904242417284168344909434697989185734657269001196015046557;
      21184885552783014549060675846140600822277, -2234786260962214395057778168210379630558628776186659249355006006, -458719484103615854767592843480630244316465005286059364293]
  | 12 => !![-7568871475599879318615494427362040386132931557973192133023, 798437638122493849566817061822586803462587573013058647435990288652536864772267394, 163889902066411793155660975041503369793202403764529325180241567765841053407;
      -16609336860480083393048993687831440599548309, 1051267916721769385430408468203534804182295101612365447039121422717, 323680001418035230498265797017229706595881758496441819144024;
      -64733797612569202873837960047171502719982926549826, -98330595305348382681839716992116044346434048408778770229418836133, 1051267921767683710570182870647056082469227789093480505185774429940]
  | 13 => !![23127894320517834523555525446920753802940990192252537635945006121574, 35131256014155619666050945425265590906600068677474693637321705775971358232185757567, -375593805614649812105616984786224884998248051419363664543406603551277860836213836060;
      (334966355937720671054534164195696040889096987992351277 / 11), 69383682906048445228185328689186497625851532959609510833317362477144, -494527935259898648866603532902965468762599347631739123508419842813403;
      -2848287089826302567308447904580724393617332430634143, 225348615341316222159752272117270687782347385804182485486937303920351297140, 57819735766603924411913317112068880718690027279581225276273843747804]
  | 14 => !![1017627348271117802159942968634180289431313085696638488306446825948557, -80511867882087850929820310673369190562578139262685256863584015465262548368924522174539048860, -20657659333594086767377119093148511561173661175812473123681984427557871926097113587796;
      2009798147282756583307559698587588444628606829491538824, -106006454825552318544457051583726359465591250809669598599185671583676958882043, -38078651406664996534963833252685194223663588081698766967504228256933420;
      6527546688736386055163785823416533163216793370382552763942940, 12394173858644894407146321725141236865780870033510505598830976995348111647324, -106006455461569411977100220114772847698348938715259898674579149622689240107887]
  | 15 => !![-2332142027150715066069859763591811817363742239535076867224708965180457500023060, -4428152738828434147671866553811049705068749056320306004635044781750730988819491966009845816276, 37873663984326731631670797825063326127599505718399364787190333299931156867255632011610616476413;
      -3070629398512885041797961719597925307899977942587994632187442753, -8162497105521784599103724671516188479052190461637884266233969731924828402703020, 49866596642338963292671688967462494969477793710305498945501886582839836897452314;
      359015068311304645186390131772350874683733893484555980877323604, -22723425171518357655239200808656399201801504050540689504056169659051237720266976594447, -6996426095444521067355622250253687154370352135770025380813599086075246761516263]
  | 16 => !![-128267811647205461421395204582079661480982180649685336469081126025655673830631996, 8118556231050279730952256382157808342850293261949188946892922980190280163100382818956630755604053573853, 2499661835463448090933725016844940416678455617260064917157899012992425754808104901922003962334437;
      -236438466117347899329801325373237013266999820440101377622642692420, 10689347855530137394117178747445305831125389014089924922104464391286461239560389779900634, 4388260572980364267807180353302953333000137853668374203146676014902648086675749293;
      -658216685780090853065800399344138488418879353218917601719822600435199037, -1499746068818686733579276814623082344534902943399622713972801969673712577597499999981703, 10689347932490824444006910488357150583915947712163798415574743580236051186388104156579527]
  | 17 => !![235165655502460286689749196372970836117748450605083885149364693792222071686954020848120263, 535824713928350849174139539772587578230867482924031801629324932736060846276245736506615518643576063084997, -3819057717230096265349395241171116102507130820071890285112273312415205550469093794085944924123060908400773;
      309632331636183341256320600104702826865265001212693488059694671767575717614, 940662625960489719419531504299205730457129923158094439275788149424070967796604628284021133, -5028386225338209069965501629150730856404143764063969224750021289395468854176501423929526503;
      -43442301478690111004313057666538470139088562851332965214830079205191192613, 2291356661428396670584768488551402327516719149633941917072175005721333648172876438715836195229287, 823079798703090650535455488927277074034054498324292656704465970041474404746335482561646336]
  | 18 => !![15520933340764404387018553233726834460378734793699293498071412242037775330846159924011673087, -818648938739857854962575437924165577254509857111222741071437866615486869183543970784307571762649242619633199815013, -294067447049668832619434782908297357005376102075611200035991095318937868475234409484240484468704022924664064;
      27247645609032941539060175679151034970289770654440979585017640467321830269143, -1077879244499312342781855637828427646710963941027880455435852068320989870051627021728439924042923143, -497810247127190602861175836906416872744248208177132662611855308769756140145375347770908841023;
      66372440608818476408137239063136215136298114958390810461125628404890694167612148677, 176434464623699763090342289431759003966894078153811749007686473040669976991565562892509522102710016, -1077879253553190128515852793718438024911011755402479937003071292070115540507845473938130232221032839]
  | _ => 0

theorem certificate_zero : certificate 0 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem certificate_step (n : Fin 18) :
    certificate (n.val + 1) = certificate n.val * witness := by
  fin_cases n <;> ext i j <;> fin_cases i <;> fin_cases j <;>
    norm_num [certificate, witness, Matrix.mul_apply, Fin.sum_univ_succ]

theorem power_certificate (n : ℕ) (hn : n ≤ 18) :
    witness ^ n = certificate n := by
  induction n with
  | zero => simpa using certificate_zero.symm
  | succ n ih =>
    have hlt : n < 18 := by omega
    rw [pow_succ, ih (by omega)]
    exact (certificate_step ⟨n, hlt⟩).symm

theorem integral_pow_5 : IntegralMatrix (witness ^ 5) := by
  rw [integralMatrix_iff_den, power_certificate 5 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem integral_pow_7 : IntegralMatrix (witness ^ 7) := by
  rw [integralMatrix_iff_den, power_certificate 7 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem integral_pow_14 : IntegralMatrix (witness ^ 14) := by
  rw [integralMatrix_iff_den, power_certificate 14 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem integral_pow_15 : IntegralMatrix (witness ^ 15) := by
  rw [integralMatrix_iff_den, power_certificate 15 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem integral_pow_16 : IntegralMatrix (witness ^ 16) := by
  rw [integralMatrix_iff_den, power_certificate 16 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem integral_pow_17 : IntegralMatrix (witness ^ 17) := by
  rw [integralMatrix_iff_den, power_certificate 17 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem integral_pow_18 : IntegralMatrix (witness ^ 18) := by
  rw [integralMatrix_iff_den, power_certificate 18 (by omega)]
  intro i j
  fin_cases i <;> fin_cases j <;> norm_num [certificate]

theorem nonintegral_pow_9 : ¬ IntegralMatrix (witness ^ 9) := by
  intro h
  have hd := (integralMatrix_iff_den _).mp h 1 0
  rw [power_certificate 9 (by omega)] at hd
  have bad : ((certificate 9) 1 0).den ≠ 1 := by norm_num [certificate]
  exact bad hd

theorem nonintegral_pow_11 : ¬ IntegralMatrix (witness ^ 11) := by
  intro h
  have hd := (integralMatrix_iff_den _).mp h 1 0
  rw [power_certificate 11 (by omega)] at hd
  have bad : ((certificate 11) 1 0).den ≠ 1 := by norm_num [certificate]
  exact bad hd

theorem nonintegral_pow_13 : ¬ IntegralMatrix (witness ^ 13) := by
  intro h
  have hd := (integralMatrix_iff_den _).mp h 1 0
  rw [power_certificate 13 (by omega)] at hd
  have bad : ((certificate 13) 1 0).den ≠ 1 := by norm_num [certificate]
  exact bad hd

end SemigroupDimension

/-! Source section: SemigroupDimension/UpperBound.lean -/


set_option maxHeartbeats 0
set_option maxRecDepth 10000

namespace SemigroupDimension

theorem tail_inSemigroup (n : ℕ) (hn : 14 ≤ n) : InSemigroup n := by
  induction n using Nat.strong_induction_on with
  | h n ih =>
    by_cases hsmall : n < 19
    · interval_cases n
      · exact ⟨0, 2, 0, 0, rfl⟩
      · exact ⟨3, 0, 0, 0, rfl⟩
      · exact ⟨0, 0, 1, 0, rfl⟩
      · exact ⟨2, 1, 0, 0, rfl⟩
      · exact ⟨0, 0, 0, 1, rfl⟩
    · have hlt : n - 5 < n := by omega
      have htail : 14 ≤ n - 5 := by omega
      have heq : n = (n - 5) + 5 := by omega
      rw [heq]
      exact inSemigroup_add (ih (n - 5) hlt htail) inSemigroup_five

theorem inSemigroup_iff (n : ℕ) :
    InSemigroup n ↔ n = 0 ∨ n = 5 ∨ n = 7 ∨ n = 10 ∨ n = 12 ∨ 14 ≤ n := by
  constructor
  · rintro ⟨a, b, c, d, h⟩
    by_cases hn : 14 ≤ n
    · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr hn))))
    · have hc : c = 0 := by omega
      have hd : d = 0 := by omega
      have ha : a ≤ 2 := by omega
      have hb : b ≤ 1 := by omega
      subst c d
      interval_cases a <;> interval_cases b <;> omega
  · rintro (rfl | rfl | rfl | rfl | rfl | h)
    · exact inSemigroup_zero
    · exact inSemigroup_five
    · exact inSemigroup_seven
    · exact ⟨2, 0, 0, 0, rfl⟩
    · exact ⟨1, 1, 0, 0, rfl⟩
    · exact tail_inSemigroup n h

theorem not_inSemigroup_thirteen : ¬ InSemigroup 13 := by
  rw [inSemigroup_iff]
  omega

theorem integral_pow_ten : IntegralMatrix (witness ^ 10) := by
  simpa only [← pow_add] using integralMatrix_mul integral_pow_5 integral_pow_5

theorem integral_pow_twelve : IntegralMatrix (witness ^ 12) := by
  simpa only [← pow_add] using integralMatrix_mul integral_pow_5 integral_pow_7

theorem tail_integral (n : ℕ) (hn : 14 ≤ n) : IntegralMatrix (witness ^ n) := by
  induction n using Nat.strong_induction_on with
  | h n ih =>
    by_cases hsmall : n < 19
    · interval_cases n
      · exact integral_pow_14
      · exact integral_pow_15
      · exact integral_pow_16
      · exact integral_pow_17
      · exact integral_pow_18
    · have hlt : n - 5 < n := by omega
      have htail : 14 ≤ n - 5 := by omega
      rw [show n = (n - 5) + 5 by omega, pow_add]
      exact integralMatrix_mul (ih (n - 5) hlt htail) integral_pow_5

theorem nonintegral_small_gaps (n : ℕ)
    (hg : n = 1 ∨ n = 2 ∨ n = 3 ∨ n = 4 ∨ n = 6 ∨ n = 8 ∨
      n = 9 ∨ n = 11 ∨ n = 13) : ¬ IntegralMatrix (witness ^ n) := by
  rintro h
  rcases hg with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · apply nonintegral_pow_11
    simpa only [← pow_add] using integralMatrix_mul h integral_pow_ten
  · apply nonintegral_pow_9
    simpa only [← pow_add] using integralMatrix_mul h integral_pow_7
  · apply nonintegral_pow_13
    simpa only [← pow_add] using integralMatrix_mul h integral_pow_ten
  · apply nonintegral_pow_9
    simpa only [← pow_add] using integralMatrix_mul h integral_pow_5
  · apply nonintegral_pow_11
    simpa only [← pow_add] using integralMatrix_mul h integral_pow_5
  · apply nonintegral_pow_13
    simpa only [← pow_add] using integralMatrix_mul h integral_pow_5
  · exact nonintegral_pow_9 h
  · exact nonintegral_pow_11 h
  · exact nonintegral_pow_13 h

/-- The explicit matrix has exactly the requested exponent semigroup,
    for every natural number, without a bound on the exponent. -/
theorem witness_realizes : Realizes witness := by
  intro n
  rw [inSemigroup_iff]
  constructor
  · intro h
    by_contra hbad
    have hg : n = 1 ∨ n = 2 ∨ n = 3 ∨ n = 4 ∨ n = 6 ∨ n = 8 ∨
        n = 9 ∨ n = 11 ∨ n = 13 := by omega
    exact nonintegral_small_gaps n hg h
  · rintro (rfl | rfl | rfl | rfl | rfl | h)
    · simpa using integralMatrix_one 3
    · exact integral_pow_5
    · exact integral_pow_7
    · exact integral_pow_ten
    · exact integral_pow_twelve
    · exact tail_integral n h

theorem dimension_at_most_three : Realizable 3 := ⟨witness, witness_realizes⟩

end SemigroupDimension

/-! Source section: SemigroupDimension/LowerBound.lean -/


set_option maxHeartbeats 0
set_option maxRecDepth 10000

namespace SemigroupDimension

theorem integralMatrix_entry_integer {n : ℕ} {M : QMatrix n}
    (hM : IntegralMatrix M) (i j : Fin n) : ∃ z : ℤ, (z : ℚ) = M i j :=
  ⟨(M i j).num, Rat.coe_int_num_of_den_eq_one ((integralMatrix_iff_den M).mp hM i j)⟩

theorem rational_integer_of_fifth_power (q : ℚ)
    (h : ∃ z : ℤ, (z : ℚ) = q ^ 5) : ∃ z : ℤ, (z : ℚ) = q := by
  rcases h with ⟨z, hz⟩
  have hp : IsIntegral ℤ (q ^ 5) := by
    rw [← hz]
    exact isIntegral_algebraMap
  have hq : IsIntegral ℤ q := IsIntegral.of_pow (by norm_num) hp
  simpa using (IsIntegrallyClosed.algebraMap_eq_of_integral (R := ℤ) (K := ℚ) hq)

theorem integralMatrix_trace_integer {n : ℕ} {M : QMatrix n}
    (hM : IntegralMatrix M) : ∃ z : ℤ, (z : ℚ) = Matrix.trace M := by
  rcases hM with ⟨N, rfl⟩
  refine ⟨Matrix.trace N, ?_⟩
  simpa [castMatrix] using AddMonoidHom.map_trace (Int.castRingHom ℚ) N

theorem integralMatrix_det_integer {n : ℕ} {M : QMatrix n}
    (hM : IntegralMatrix M) : ∃ z : ℤ, (z : ℚ) = Matrix.det M := by
  rcases hM with ⟨N, rfl⟩
  refine ⟨Matrix.det N, ?_⟩
  simpa [castMatrix] using (Int.castRingHom ℚ).map_det N

theorem two_by_two_cayley_hamilton (M : QMatrix 2) :
    M ^ 2 = Matrix.trace M • M - Matrix.det M • (1 : QMatrix 2) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [pow_two, Matrix.mul_apply, Fin.sum_univ_succ,
      Matrix.trace_fin_two, Matrix.det_fin_two, Matrix.smul_apply] <;> ring

def lucas (t d : ℚ) : ℕ → ℚ
  | 0 => 0
  | 1 => 1
  | n + 2 => t * lucas t d (n + 1) - d * lucas t d n

theorem matrix_power_lucas (M : QMatrix 2) (n : ℕ) :
    M ^ (n + 1) = lucas (Matrix.trace M) (Matrix.det M) (n + 1) • M -
      (Matrix.det M * lucas (Matrix.trace M) (Matrix.det M) n) • (1 : QMatrix 2) := by
  induction n with
  | zero => simp [lucas]
  | succ n ih =>
    have hm : M * M = Matrix.trace M • M - Matrix.det M • (1 : QMatrix 2) := by
      simpa only [pow_two] using two_by_two_cayley_hamilton M
    rw [pow_succ, ih, sub_mul, smul_mul_assoc, smul_mul_assoc, one_mul, hm]
    simp only [smul_sub, smul_smul]
    ext i j
    simp only [Matrix.sub_apply, Matrix.smul_apply, smul_eq_mul, lucas]
    ring

theorem two_by_two_trace_fifth (M : QMatrix 2) :
    Matrix.trace (M ^ 5) = (Matrix.trace M) ^ 5 -
      5 * Matrix.det M * (Matrix.trace M) ^ 3 +
      5 * (Matrix.det M) ^ 2 * Matrix.trace M := by
  rw [show M ^ 5 = _ from matrix_power_lucas M 4]
  simp [Matrix.trace_sub, Matrix.trace_smul, Matrix.trace_one, lucas]
  ring

/-- The trace and determinant are integers whenever the fifth power is an integer matrix.
    The trace argument uses the monic rational-root theorem. -/
theorem two_by_two_trace_det_integer (M : QMatrix 2)
    (h5 : IntegralMatrix (M ^ 5)) :
    (∃ t : ℤ, (t : ℚ) = Matrix.trace M) ∧
    (∃ d : ℤ, (d : ℚ) = Matrix.det M) := by
  have hd5 := integralMatrix_det_integer h5
  rw [Matrix.det_pow] at hd5
  obtain ⟨d, hd⟩ := rational_integer_of_fifth_power (Matrix.det M) hd5
  obtain ⟨z, hz⟩ := integralMatrix_trace_integer h5
  let f : Polynomial ℤ := Polynomial.X ^ 5 -
    Polynomial.C (5 * d) * Polynomial.X ^ 3 +
    Polynomial.C (5 * d ^ 2) * Polynomial.X - Polynomial.C z
  have hf : f.Monic := by
    dsimp [f]
    monicity!
  have hroot : Polynomial.aeval (Matrix.trace M) f = 0 := by
    simp only [f, map_sub, map_add, map_mul, map_pow, Polynomial.aeval_C,
      Polynomial.aeval_X]
    change Matrix.trace M ^ 5 - 5 * (d : ℚ) * Matrix.trace M ^ 3 +
      5 * (d : ℚ) ^ 2 * Matrix.trace M - (z : ℚ) = 0
    rw [hd]
    rw [two_by_two_trace_fifth] at hz
    exact sub_eq_zero.mpr hz.symm
  have ht : IsIntegral ℤ (Matrix.trace M) := ⟨f, hf, hroot⟩
  obtain ⟨t, ht⟩ := IsIntegrallyClosed.algebraMap_eq_of_integral (R := ℤ) (K := ℚ) ht
  exact ⟨⟨t, by simpa using ht⟩, ⟨d, hd⟩⟩

def lowerP (t d : ℚ) : ℚ :=
  d ^ 4 - 18 * d ^ 3 * t ^ 2 + 7 * d ^ 2 * t ^ 4 + 6 * d * t ^ 6 - 2 * t ^ 8

def lowerQ (t d : ℚ) : ℚ := t ^ 4 * (-8 * d + 3 * t ^ 2)

def lowerR (t d : ℚ) : ℚ := 4 * d ^ 6 * t + 2 * d ^ 5 * t ^ 3

/-- An exact identity valid for every rational 2×2 matrix. -/
theorem two_by_two_thirteenth_identity (M : QMatrix 2) :
    M ^ 13 = lowerP (Matrix.trace M) (Matrix.det M) • (M ^ 5) +
      lowerQ (Matrix.trace M) (Matrix.det M) • (M ^ 7) +
      lowerR (Matrix.trace M) (Matrix.det M) • (1 : QMatrix 2) := by
  rw [show M ^ 13 = _ from matrix_power_lucas M 12,
    show M ^ 5 = _ from matrix_power_lucas M 4,
    show M ^ 7 = _ from matrix_power_lucas M 6]
  ext i j
  simp only [Matrix.add_apply, Matrix.sub_apply, Matrix.smul_apply, smul_eq_mul]
  simp only [lowerP, lowerQ, lowerR, lucas]
  ring

/-- Integral fifth and seventh powers of a rational 2×2 matrix force its
    thirteenth power to be integral. No published theorem is assumed. -/
theorem two_by_two_thirteenth_integral (M : QMatrix 2)
    (h5 : IntegralMatrix (M ^ 5)) (h7 : IntegralMatrix (M ^ 7)) :
    IntegralMatrix (M ^ 13) := by
  obtain ⟨⟨t, ht⟩, ⟨d, hd⟩⟩ := two_by_two_trace_det_integer M h5
  let P : ℤ := d ^ 4 - 18 * d ^ 3 * t ^ 2 + 7 * d ^ 2 * t ^ 4 +
    6 * d * t ^ 6 - 2 * t ^ 8
  let Q : ℤ := t ^ 4 * (-8 * d + 3 * t ^ 2)
  let R : ℤ := 4 * d ^ 6 * t + 2 * d ^ 5 * t ^ 3
  have hp : lowerP (Matrix.trace M) (Matrix.det M) = (P : ℚ) := by
    rw [← ht, ← hd]
    simp [lowerP, P]
  have hq : lowerQ (Matrix.trace M) (Matrix.det M) = (Q : ℚ) := by
    rw [← ht, ← hd]
    simp [lowerQ, Q]
  have hr : lowerR (Matrix.trace M) (Matrix.det M) = (R : ℚ) := by
    rw [← ht, ← hd]
    simp [lowerR, R]
  rw [two_by_two_thirteenth_identity M, hp, hq, hr]
  exact integralMatrix_add
    (integralMatrix_add (integralMatrix_int_smul P h5) (integralMatrix_int_smul Q h7))
    (integralMatrix_int_smul R (integralMatrix_one 2))

theorem not_realizable_two : ¬ Realizable 2 := by
  rintro ⟨M, hM⟩
  have h5 := (hM 5).mpr inSemigroup_five
  have h7 := (hM 7).mpr inSemigroup_seven
  exact not_inSemigroup_thirteen ((hM 13).mp (two_by_two_thirteenth_integral M h5 h7))

theorem fin_one_power (M : QMatrix 1) (n : ℕ) : (M ^ n) 0 0 = (M 0 0) ^ n := by
  induction n with
  | zero => simp
  | succ n ih => simp [pow_succ, Matrix.mul_apply, Fin.sum_univ_succ, ih]

theorem not_realizable_one : ¬ Realizable 1 := by
  rintro ⟨M, hM⟩
  obtain ⟨z, hz⟩ := integralMatrix_entry_integer ((hM 5).mpr inSemigroup_five) 0 0
  rw [fin_one_power] at hz
  obtain ⟨q, hq⟩ := rational_integer_of_fifth_power (M 0 0) ⟨z, hz⟩
  have hi : IntegralMatrix M := by
    rw [integralMatrix_iff_den]
    intro i j
    fin_cases i
    fin_cases j
    change (M 0 0).den = 1
    rw [← hq]
    exact Rat.den_intCast q
  have h1 : InSemigroup 1 := (hM 1).mp (by simpa using hi)
  rw [inSemigroup_iff] at h1
  omega

theorem not_realizable_zero : ¬ Realizable 0 := by
  rintro ⟨M, hM⟩
  have hi : IntegralMatrix (M ^ 1) := by
    rw [integralMatrix_iff_den]
    intro i
    exact Fin.elim0 i
  have h1 := (hM 1).mp hi
  rw [inSemigroup_iff] at h1
  omega

theorem dimension_at_least_three (k : ℕ) (hk : Realizable k) : 3 ≤ k := by
  by_contra h
  have hlt : k < 3 := by omega
  interval_cases k
  · exact not_realizable_zero hk
  · exact not_realizable_one hk
  · exact not_realizable_two hk

end SemigroupDimension

/-! Source section: SemigroupDimension.lean -/


namespace SemigroupDimension

/-- The matricial dimension of the semigroup generated by 5, 7, 16, 18 is exactly 3. -/
theorem hasMatricialDimension_three : HasMatricialDimension 3 :=
  ⟨dimension_at_most_three, dimension_at_least_three⟩

/-- The least dimension of a rational matrix realizing the stated semigroup. -/
noncomputable def matricialDimension : ℕ := by
  classical
  exact Nat.find (show ∃ d, Realizable d from ⟨3, dimension_at_most_three⟩)

theorem matricial_dimension_eq_three : matricialDimension = 3 := by
  classical
  unfold matricialDimension
  apply Nat.le_antisymm
  · exact Nat.find_min' _ dimension_at_most_three
  · exact dimension_at_least_three _ (Nat.find_spec _)

#print axioms witness_realizes
#print axioms two_by_two_thirteenth_integral
#print axioms hasMatricialDimension_three
#print axioms matricial_dimension_eq_three

end SemigroupDimension
