import SemigroupDimension.UpperBound
import SemigroupDimension.LowerBound

namespace SemigroupDimension

/-- The matricial dimension of the semigroup generated by 5, 7, 16, 18 is exactly 3. -/
theorem hasMatricialDimension_three : HasMatricialDimension 3 :=
  ⟨dimension_at_most_three, dimension_at_least_three⟩

/-- The least dimension of a rational matrix realizing the stated semigroup. -/
noncomputable def matricialDimension : ℕ := by
  classical
  exact Nat.find (show ∃ d, Realizable d from ⟨3, dimension_at_most_three⟩)

theorem matricial_dimension_eq_three : matricialDimension = 3 := by
  classical
  unfold matricialDimension
  apply Nat.le_antisymm
  · exact Nat.find_min' _ dimension_at_most_three
  · exact dimension_at_least_three _ (Nat.find_spec _)

#print axioms witness_realizes
#print axioms two_by_two_thirteenth_integral
#print axioms hasMatricialDimension_three
#print axioms matricial_dimension_eq_three

end SemigroupDimension
