import Mathlib.Data.Matrix.Notation
import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.RingTheory.Polynomial.RationalRoot
import Mathlib.Tactic

/-!
# Matricial dimension of the numerical semigroup generated by 5, 7, 16, 18

All matrices use Mathlib's `Matrix`, all entries are in `ℚ`, and integrality
means membership in the image of integer matrices under entrywise casting.
The target semigroup is defined by arbitrary nonnegative integer combinations
of its four stated generators.
-/

set_option maxHeartbeats 0
set_option maxRecDepth 10000

namespace SemigroupDimension

abbrev QMatrix (n : ℕ) := Matrix (Fin n) (Fin n) ℚ
abbrev ZMatrix (n : ℕ) := Matrix (Fin n) (Fin n) ℤ

def castMatrix (n : ℕ) : ZMatrix n →+* QMatrix n :=
  (Int.castRingHom ℚ).mapMatrix

def IntegralMatrix {n : ℕ} (M : QMatrix n) : Prop :=
  M ∈ (castMatrix n).range

def InSemigroup (n : ℕ) : Prop :=
  ∃ a b c d : ℕ, n = 5 * a + 7 * b + 16 * c + 18 * d

def Realizes {d : ℕ} (M : QMatrix d) : Prop :=
  ∀ n : ℕ, IntegralMatrix (M ^ n) ↔ InSemigroup n

def Realizable (d : ℕ) : Prop := ∃ M : QMatrix d, Realizes M

/-- A dimension is minimal among all matrix representations. -/
def HasMatricialDimension (d : ℕ) : Prop :=
  Realizable d ∧ ∀ k : ℕ, Realizable k → d ≤ k

theorem integralMatrix_iff_den {n : ℕ} (M : QMatrix n) :
    IntegralMatrix M ↔ ∀ i j, (M i j).den = 1 := by
  constructor
  · rintro ⟨N, rfl⟩ i j
    change ((N i j : ℚ)).den = 1
    exact Rat.den_intCast _
  · intro h
    refine ⟨fun i j => (M i j).num, ?_⟩
    ext i j
    exact Rat.coe_int_num_of_den_eq_one (h i j)

theorem integralMatrix_one (n : ℕ) : IntegralMatrix (1 : QMatrix n) :=
  (castMatrix n).range.one_mem

theorem integralMatrix_mul {n : ℕ} {M N : QMatrix n}
    (hM : IntegralMatrix M) (hN : IntegralMatrix N) : IntegralMatrix (M * N) :=
  (castMatrix n).range.mul_mem hM hN

theorem integralMatrix_add {n : ℕ} {M N : QMatrix n}
    (hM : IntegralMatrix M) (hN : IntegralMatrix N) : IntegralMatrix (M + N) :=
  (castMatrix n).range.add_mem hM hN

theorem integralMatrix_pow {n : ℕ} {M : QMatrix n}
    (hM : IntegralMatrix M) (k : ℕ) : IntegralMatrix (M ^ k) :=
  (castMatrix n).range.pow_mem hM k

theorem integralMatrix_int_smul {n : ℕ} (z : ℤ) {M : QMatrix n}
    (hM : IntegralMatrix M) : IntegralMatrix ((z : ℚ) • M) := by
  rcases hM with ⟨N, rfl⟩
  refine ⟨fun i j => z * N i j, ?_⟩
  ext i j
  simp [castMatrix, Matrix.smul_apply, smul_eq_mul]

theorem inSemigroup_zero : InSemigroup 0 := ⟨0, 0, 0, 0, rfl⟩
theorem inSemigroup_five : InSemigroup 5 := ⟨1, 0, 0, 0, rfl⟩
theorem inSemigroup_seven : InSemigroup 7 := ⟨0, 1, 0, 0, rfl⟩

theorem inSemigroup_add {m n : ℕ} (hm : InSemigroup m) (hn : InSemigroup n) :
    InSemigroup (m + n) := by
  rcases hm with ⟨a, b, c, d, rfl⟩
  rcases hn with ⟨e, f, g, h, rfl⟩
  refine ⟨a + e, b + f, c + g, d + h, ?_⟩
  omega

def witness : QMatrix 3 :=
  !![0, 0, -357276958458978899;
    1 / 34522712143931, 0, -833361690 / 1771561;
    0, 214358881, -11]

end SemigroupDimension
